name: "Mocha Test"
on:
    pull_request:
        branches:
            - master


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: 'Install Node'
              uses: actions/setup-node@v1
            - name: Install dependencies & dev dependencies
              run: npm install -D
            - name: "Run Test"
              run: npm run test

